# Generated by Django 3.2.9 on 2022-05-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_order',
            old_name='Payment_Opetion',
            new_name='Payment_Option',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='product',
        ),
        migrations.AddField(
            model_name='customer_order',
            name='castel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='doppel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='george',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='senq',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='total_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
