# Generated by Django 3.2.9 on 2022-05-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20220511_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='castel',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='doppel',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='george',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='senq',
        ),
        migrations.AddField(
            model_name='customer_order',
            name='Castle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='Doppel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='Sinq_Malt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='St_George',
            field=models.IntegerField(default=0),
        ),
    ]
