# Generated by Django 3.2.9 on 2022-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20220514_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='newone',
            field=models.IntegerField(default=0),
        ),
    ]
