# Generated by Django 3.2.9 on 2022-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20220515_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='Payment_Option',
        ),
        migrations.AddField(
            model_name='customer_order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
