# Generated by Django 3.2.9 on 2022-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_auto_20220509_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stor_Name', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
