# Generated by Django 3.2.9 on 2022-05-10 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agent', '0003_stor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agent.stor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
