# Generated by Django 3.2.9 on 2022-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_auto_20220509_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_manager',
            name='Telegram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store_manager',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store_manager',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store_manager',
            name='instagrm',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
