# Generated by Django 3.2.9 on 2022-05-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20220509_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stor',
            new_name='Agent_Store',
        ),
        migrations.RenameField(
            model_name='agent_store',
            old_name='Stor_Name',
            new_name='Store_Name',
        ),
    ]
