# Generated by Django 3.2.9 on 2022-05-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_auto_20220509_2353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Root',
            new_name='Route',
        ),
    ]
