# Generated by Django 3.2.9 on 2022-05-10 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0023_auto_20220509_2340'),
        ('Agent', '0009_auto_20220510_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='vichel',
            name='Agent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.agent'),
        ),
        migrations.CreateModel(
            name='Diraver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=200, null=True)),
                ('Adderes', models.CharField(max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Telegram', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('instagrm', models.CharField(max_length=200, null=True)),
                ('Agent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.agent')),
                ('Vichel', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agent.vichel')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
