# Generated by Django 3.2.9 on 2022-05-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_auto_20220509_2340'),
        ('Agent', '0010_auto_20220510_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('castel', 'castel'), ('senq', 'senq'), ('doppel', 'doppel'), ('george', 'george')], max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Agent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.agent')),
                ('Store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Agent.agent_store')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('Payment_Opetion', models.CharField(choices=[('CBE', 'CBE'), ('TellBirr', 'TellBirr')], max_length=200, null=True)),
                ('Agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.agent')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.product')),
            ],
        ),
    ]
