# Generated by Django 3.2.9 on 2022-05-11 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0031_delete_region_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agent', '0012_auto_20220510_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store_Manager',
            new_name='Agent_Store_Manager',
        ),
    ]
