# Generated by Django 3.2.9 on 2022-05-11 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0031_delete_region_manager'),
        ('Agent', '0013_rename_store_manager_agent_store_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diraver',
            new_name='Driver',
        ),
        migrations.RenameModel(
            old_name='Vichel',
            new_name='Vehicle',
        ),
    ]
