# Generated by Django 3.2.9 on 2022-05-11 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0031_delete_region_manager'),
        ('Agent', '0014_auto_20220511_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent_fince',
            new_name='Agent_finance',
        ),
    ]
