# Generated by Django 3.2.9 on 2022-05-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Company', '0033_auto_20220511_0944'),
        ('Agent', '0015_rename_agent_fince_agent_finance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_in_Agent_Stor',
        ),
    ]
