# Generated by Django 3.2.9 on 2022-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0016_rename_product_product_in_agent_stor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_in_agent_stor',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
