# Generated by Django 3.2.9 on 2022-05-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0018_auto_20220517_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_order',
            name='product',
        ),
    ]
