# Generated by Django 3.2.9 on 2022-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0018_auto_20220517_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
