# Generated by Django 3.2.9 on 2022-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0019_agent_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_order',
            name='total_payment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
