# Generated by Django 3.2.9 on 2022-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='Region_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
