# Generated by Django 3.2.9 on 2022-05-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_rgeion_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stor_Name', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
