# Generated by Django 3.2.9 on 2022-05-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_stor_manager_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=200, null=True)),
                ('product_Quintitiy', models.CharField(max_length=200, null=True)),
                ('Stor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.stor')),
            ],
        ),
    ]
