# Generated by Django 3.2.9 on 2022-05-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.product')),
            ],
        ),
    ]
