# Generated by Django 3.2.9 on 2022-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_finace_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='Compan_name',
            new_name='Agent_name',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='Rooting',
            new_name='Region',
        ),
        migrations.AddField(
            model_name='agent',
            name='Area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='Location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='TIN_Number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
