# Generated by Django 3.2.9 on 2022-05-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_auto_20220501_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/'),
        ),
    ]
