# Generated by Django 3.2.9 on 2022-05-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_agent_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Agreement_Paper',
            field=models.FileField(blank=True, null=True, upload_to='license'),
        ),
        migrations.AddField(
            model_name='agent',
            name='License',
            field=models.FileField(blank=True, null=True, upload_to='license'),
        ),
    ]
