# Generated by Django 3.2.9 on 2022-05-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_alter_agent_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='Adderes',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='Agent_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='Area',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='Location',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='TIN_Number',
            new_name='phone2',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='Telegram',
            new_name='telegram',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='Agreement_Paper',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='instagrm',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='phone',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='TIN_NO',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='Agreement'),
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='License',
            field=models.FileField(blank=True, null=True, upload_to='License'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
