# Generated by Django 3.2.9 on 2022-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_rgeion_manager_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgeion_manager',
            name='Full_Name',
        ),
        migrations.AddField(
            model_name='agent',
            name='Full_Name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
