# Generated by Django 3.2.9 on 2022-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0020_auto_20220502_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
