# Generated by Django 3.2.9 on 2022-05-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_auto_20220503_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.region'),
        ),
    ]
