# Generated by Django 3.2.9 on 2022-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0022_agent_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Product_Price',
        ),
    ]
