# Generated by Django 3.2.9 on 2022-05-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0023_auto_20220509_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stor',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Stor_Name',
            new_name='Store_Name',
        ),
    ]
