# Generated by Django 3.2.9 on 2022-05-11 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0024_auto_20220511_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rgeion_Manager',
            new_name='Region_Manager',
        ),
    ]
