# Generated by Django 3.2.9 on 2022-05-11 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0027_rename_rgeion_manager_region_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stor_Manager',
            new_name='Manager',
        ),
    ]
