# Generated by Django 3.2.9 on 2022-05-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0030_rename_finace_manager_finance_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region_Manager',
        ),
    ]
