# Generated by Django 3.2.9 on 2022-05-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0032_rename_s_manager_company_store_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Company_Store',
        ),
        migrations.RenameField(
            model_name='company_store_manager',
            old_name='Stor',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stor',
            new_name='Store',
        ),
    ]
