# Generated by Django 3.2.9 on 2022-05-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0033_auto_20220511_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_store_manager',
            name='staff',
            field=models.CharField(default='company_store_manager', max_length=50),
        ),
        migrations.AddField(
            model_name='finance_manager',
            name='staff',
            field=models.CharField(default='Finance_manager', max_length=50),
        ),
    ]
