# Generated by Django 3.2.9 on 2022-05-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0034_auto_20220511_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_store_manager',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/'),
        ),
        migrations.AddField(
            model_name='finance_manager',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile/'),
        ),
    ]
