# Generated by Django 3.2.9 on 2022-05-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0035_auto_20220511_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_store_manager',
            name='staff',
            field=models.CharField(default='Store Manager', max_length=50),
        ),
        migrations.AlterField(
            model_name='finance_manager',
            name='staff',
            field=models.CharField(default='Finance manager', max_length=50),
        ),
    ]
