# Generated by Django 3.2.9 on 2022-05-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0036_auto_20220511_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_store_manager',
            name='staff',
            field=models.CharField(default='Store_Manager', max_length=50),
        ),
        migrations.AlterField(
            model_name='finance_manager',
            name='staff',
            field=models.CharField(default='Finance_manager', max_length=50),
        ),
    ]
