# Generated by Django 3.2.9 on 2022-05-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0037_auto_20220511_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_store_manager',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finance_manager',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
