# Generated by Django 3.2.9 on 2022-05-12 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0039_auto_20220512_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_Quintitiy',
        ),
    ]
