# Generated by Django 3.2.9 on 2022-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0040_auto_20220512_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='Price_in_botle',
        ),
        migrations.AddField(
            model_name='product',
            name='Price_in_creates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
