# Generated by Django 3.2.9 on 2022-05-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0041_auto_20220512_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_Name',
            new_name='Product_Name',
        ),
    ]
