# Generated by Django 3.2.9 on 2022-05-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0043_product_amount_in_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Store',
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Store',
            field=models.ManyToManyField(to='Company.Company_Store'),
        ),
    ]
