# Generated by Django 3.2.9 on 2022-05-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0044_auto_20220512_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Product_Name',
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Product_Name',
            field=models.ManyToManyField(to='Company.Product'),
        ),
    ]
