# Generated by Django 3.2.9 on 2022-05-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0046_auto_20220512_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_store',
            old_name='Location',
            new_name='Address',
        ),
    ]
