# Generated by Django 3.2.9 on 2022-05-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0047_rename_location_company_store_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_Quintitiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='product_Quintitiy',
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Quintitiy',
            field=models.ManyToManyField(to='Company.product_Quintitiy'),
        ),
    ]
