# Generated by Django 3.2.9 on 2022-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0048_auto_20220512_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Quintitiy',
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='product_Quintitiy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='product_Quintitiy',
        ),
    ]
