# Generated by Django 3.2.9 on 2022-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0049_auto_20220512_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Store',
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Store',
            field=models.ManyToManyField(null=True, to='Company.Company_Store'),
        ),
    ]
