# Generated by Django 3.2.9 on 2022-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0051_alter_product_amount_in_store_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_amount_in_store',
            old_name='Product_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product_amount_in_store',
            old_name='Store',
            new_name='produc_store',
        ),
    ]
