# Generated by Django 3.2.9 on 2022-05-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0052_auto_20220513_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_amount_in_store',
            old_name='produc_store',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='company_store_manager',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
