# Generated by Django 3.2.9 on 2022-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0058_auto_20220514_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='product_Quintitiy',
        ),
    ]
