# Generated by Django 3.2.9 on 2022-05-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0060_auto_20220514_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_amount_in_store',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company_store'),
        ),
    ]
