# Generated by Django 3.2.9 on 2022-05-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0061_alter_product_amount_in_store_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Doppel',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Sinq Malt',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='St.George',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='new',
        ),
    ]
