# Generated by Django 3.2.9 on 2022-05-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0063_auto_20220514_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_store',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
