# Generated by Django 3.2.9 on 2022-05-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0065_remove_company_store_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_store',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
