# Generated by Django 3.2.9 on 2022-05-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0066_company_store_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Castle',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Doppel',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='Sinq_Malt',
        ),
        migrations.RemoveField(
            model_name='product_amount_in_store',
            name='St_George',
        ),
    ]
