# Generated by Django 3.2.9 on 2022-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0067_auto_20220514_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='Product_img/castle-beer.jpg', null=True, upload_to='Product_img/'),
        ),
    ]
