# Generated by Django 3.2.9 on 2022-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0068_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Castle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Doppel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='Sinq_Malt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='St_George',
            field=models.IntegerField(default=0),
        ),
    ]
