# Generated by Django 3.2.9 on 2022-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0069_auto_20220514_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount_in_store',
            name='new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_amount_in_store',
            name='newone',
            field=models.IntegerField(default=0),
        ),
    ]
